import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const read = (relativePath: string) => fs.readFileSync(path.join(root, relativePath), "utf8");

const app = read("web/src/App.tsx");
const navigation = read("web/src/navigation.ts");
const sidebar = read("web/src/components/AppSidebar.tsx");
const api = read("web/src/api.ts");
const types = read("web/src/types.ts");
const view = read("web/src/components/DevicesView.tsx");
const copy = read("web/src/i18n/devices.ts");
const i18n = read("web/src/i18n.ts");
const styles = read("web/src/styles.css");
const routes = read("src/server/device-routes.ts");
const lifecycleRoutes = read("src/server/device-runtime-lifecycle-routes.ts");
const store = read("src/devices/device-registry.ts");

assert.match(navigation, /\| "devices"/);
assert.match(app, /devices:\s*consolePath\("devices"\)/);
assert.match(app, /route === "devices"/);
assert.match(app, /import\("\.\/components\/DevicesView"\)/);
assert.match(app, /activeView === "devices"/);
assert.match(app, /<DevicesView locale=\{locale\}/);
assert.match(sidebar, /key:\s*"devices"/);
assert.match(sidebar, /labels\.devices/);
assert.match(i18n, /devices:\s*"设备"/);
assert.match(i18n, /devices:\s*"Devices"/);

assert.match(api, /fetchDevices/);
assert.match(api, /fetchDeviceEnrollmentRequests/);
assert.match(api, /decideDeviceEnrollment/);
assert.match(api, /\/api\/devices\/enrollment-requests/);
assert.match(api, /revokeDevice/);
assert.match(api, /setDeviceExecutionPolicy/);
assert.match(api, /fetchDeviceRuntimeStatus/);
assert.match(api, /executeDeviceRuntimeLifecycle/);
assert.match(api, /\/api\/devices\/\$\{encodeURIComponent\(deviceId\)\}\/runtime/);
assert.match(api, /action:\s*"pause" \| "resume"/);
assert.match(api, /\/api\/devices\/\$\{encodeURIComponent\(deviceId\)\}\/\$\{action\}/);
assert.match(api, /method:\s*"DELETE"/);
assert.match(api, /buildHeaders\(null, \{ mutation: true \}\)/);

assert.match(types, /ManagedDevicePresence = "online" \| "offline"/);
assert.match(types, /ManagedDeviceExecutionPolicy = "active" \| "paused"/);
assert.match(types, /executionPolicyRevision:\s*number/);
assert.match(types, /DeviceEnrollmentStatus = "pending" \| "approved" \| "denied" \| "expired"/);
assert.match(types, /enrollmentRequests:\s*DeviceEnrollmentRequestSummary\[\]/);
assert.match(types, /verificationCode:\s*string/);
assert.match(types, /remoteRead:\s*boolean/);
assert.match(types, /remoteControl:\s*false/);
assert.match(types, /runtimeLifecycle:\s*boolean/);
assert.match(types, /DeviceRuntimeLifecycleSupport = "managed-macos" \| "unsupported"/);
assert.match(types, /DeviceRuntimeLifecycleAction = "start" \| "stop" \| "restart"/);
assert.match(types, /publicKeyFingerprint:\s*string \| null/);

assert.match(view, /Promise\.all\(\[/);
assert.match(view, /fetchDevices\(\)/);
assert.match(view, /fetchDeviceEnrollmentRequests\(\)/);
assert.match(view, /requestResponse\.enrollmentRequests/);
assert.match(view, /decideDeviceEnrollment\(requestId, decision\)/);
assert.match(view, /revokeDevice\(deviceId\)/);
assert.match(view, /window\.setInterval\([^]*10_000/);
assert.match(view, /request\.verificationCode/);
assert.match(view, /request\.publicKeyFingerprint/);
assert.match(view, /device\.presence === "online"/);
assert.doesNotMatch(view, /device\.presence === "revoked"/);
assert.match(view, /device\.trust === "revoked"/);
assert.match(view, /device\.executionPolicy === "paused"/);
assert.match(view, /setDeviceExecutionPolicy\(/);
assert.match(view, /device\.locality === "local"/);
assert.match(view, /device\.management\.heartbeat/);
assert.match(view, /device\.management\.remoteRead/);
assert.match(view, /remoteReadAgentUpdate/);
assert.match(view, /remoteReadOffline/);
assert.match(view, /device\.management\.runtimeLifecycle/);
assert.match(view, /fetchDeviceRuntimeStatus\(device\.id\)/);
assert.match(view, /executeDeviceRuntimeLifecycle\(/);
assert.match(view, /crypto\.randomUUID\(\)/);
assert.match(view, /runtime\.state === "stopped"/);
assert.match(view, /runtime\.state === "ready"/);
assert.match(view, /runRuntimeLifecycle\(device, "start"\)/);
assert.match(view, /runRuntimeLifecycle\(device, "stop"\)/);
assert.match(view, /runRuntimeLifecycle\(device, "restart"\)/);
assert.match(view, /title=\{copy\.stopRuntimeTitle\}/);
assert.match(view, /title=\{copy\.restartRuntimeTitle\}/);
assert.match(view, /Popconfirm/);
assert.doesNotMatch(view, /createDevicePairing|pairing\.code|Pairing ID|一次性配对码/);
assert.doesNotMatch(view, /channelId|lastSequence|publicKeySpki|privateKey|machineApiToken|CHATCOCKPIT_API_TOKEN/i);
assert.doesNotMatch(view, /networkInterfaces|ifconfig|arp|nmap|bonjour|mdns/i);

assert.match(copy, /title:\s*"设备"/);
assert.match(copy, /title:\s*"Devices"/);
assert.match(copy, /验证码只用于人工核对，不是登录密码或认证凭据/);
assert.match(copy, /code is for human verification only, not authentication/);
assert.match(copy, /局域网可达也不代表设备可信/);
assert.match(copy, /LAN reachability does not make a device trusted/);
assert.match(copy, /远程读取可用/);
assert.match(copy, /Remote reads ready/);
assert.match(copy, /暂停 AI 执行/);
assert.match(copy, /Pause AI execution/);
assert.match(copy, /恢复 AI 执行/);
assert.match(copy, /Resume AI execution/);
assert.match(copy, /Runtime 就绪/);
assert.match(copy, /Runtime 已停止/);
assert.match(copy, /停止 Runtime/);
assert.match(copy, /重启 Runtime/);
assert.match(copy, /Runtime ready/);
assert.match(copy, /Runtime stopped/);
assert.match(copy, /Stop Runtime/);
assert.match(copy, /Restart Runtime/);

assert.match(routes, /app\.get\("\/api\/devices"/);
assert.match(routes, /enrollmentRequests:\s*store\.listPendingEnrollmentRequests/);
assert.match(routes, /app\.post\("\/api\/devices\/enrollment-requests"/);
assert.match(routes, /\/status"/);
assert.match(routes, /\/decision"/);
assert.match(routes, /app\.post\("\/api\/devices\/heartbeat"/);
assert.match(routes, /for \(const action of \["pause", "resume"\] as const\)/);
assert.match(routes, /`\/api\/devices\/:deviceId\/\$\{action\}`/);
assert.match(routes, /executionPolicyRevision/);
assert.match(routes, /app\.delete\("\/api\/devices\/:deviceId"/);
assert.match(routes, /OPERATOR_SESSION_REQUIRED/);
assert.match(routes, /isCapabilityRpcAvailable/);
assert.match(routes, /remoteRead/);
assert.match(routes, /runtimeLifecycle/);
assert.match(routes, /isRuntimeLifecycleRpcAvailable/);
assert.match(lifecycleRoutes, /app\.get\("\/api\/devices\/:deviceId\/runtime"/);
assert.match(lifecycleRoutes, /app\.post\("\/api\/devices\/:deviceId\/runtime\/lifecycle"/);
assert.match(lifecycleRoutes, /OPERATOR_CSRF_HEADER/);
assert.doesNotMatch(routes, /privateKey|machine-token/i);

assert.match(store, /ed25519/);
assert.match(store, /DEVICE_PRESENCE_WINDOW_MS = 90_000/);
assert.match(store, /DEVICE_ENROLLMENT_TTL_MS = 5 \* 60_000/);
assert.match(store, /DEVICE_HEARTBEAT_REPLAYED/);
assert.match(store, /paused_at/);
assert.match(store, /execution_policy_revision/);
assert.match(store, /DEVICE_EXECUTION_POLICY_REVISION_CONFLICT/);
assert.match(store, /verification_code/);
assert.doesNotMatch(store, /scan|bonjour|mdns|nmap|arp -/i);

assert.match(styles, /\.device-grid/);
assert.match(styles, /\.device-card/);
assert.match(styles, /\.device-verification-code/);

process.stdout.write("VERIFY_DEVICE_UI_OK\n");
