import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");

function read(relativePath: string): string {
  const filePath = path.join(root, relativePath);
  assert.equal(fs.existsSync(filePath), true, `${relativePath} must exist`);
  return fs.readFileSync(filePath, "utf8");
}

const app = read("web/src/App.tsx");
const api = read("web/src/api.ts");
const types = read("web/src/types.ts");
const headerI18n = read("web/src/i18n.ts");
const view = read("web/src/components/PublicAccessView.tsx");
const copy = read("web/src/i18n/public-access.ts");
const styles = read("web/src/styles.css");

assert.match(app, /type ViewKey = [^;]*"publicAccess"/s);
assert.match(app, /publicAccess:\s*consolePath\("public-access"\)/);
assert.match(app, /route === "public-access"/);
assert.match(app, /import\("\.\/components\/PublicAccessView"\)/);
assert.match(app, /value:\s*"publicAccess"/);
assert.match(app, /app-toolbar__group app-toolbar__group--views/);
assert.match(app, /<PublicAccessView[\s\S]*status=\{integrationStatus\}/s);
assert.match(app, /exposed=\{health\.exposed\}/);
assert.match(app, /providerStatus=\{connectivityProviderStatus\}/);
assert.match(app, /providerStatusError=\{connectivityProviderStatusError\}/);
assert.match(app, /fetchConnectivityProviders\(token\)/);
assert.match(app, /setConnectivityProviderStatus\(providerResponse\)/);
assert.match(app, /setConnectivityProviderStatusError\(getErrorMessage\(error\)\)/);
assert.match(app, /fetchPublicRouteCandidate\(token\)/);
assert.match(app, /setPublicRouteCandidateStatus\(routeResponse\)/);
assert.match(app, /stagePublicRouteCandidate\(\{ origin, source \}, token\)/);
assert.match(app, /discardPublicRouteCandidate\(token\)/);
assert.match(app, /routeStatus=\{publicRouteCandidateStatus\}/);
assert.match(app, /routeStatusError=\{publicRouteCandidateError\}/);
assert.match(app, /routeMutating=\{publicRouteCandidateMutating\}/);
assert.match(app, /onStageCandidate=\{\(origin, source\) => void stageCandidatePublicRoute\(origin, source\)\}/);
assert.match(app, /onDiscardCandidate=\{\(\) => void discardCandidatePublicRoute\(\)\}/);
assert.match(app, /onOpenIntegrations=\{\(\) => navigateView\("integrations"\)\}/);
assert.match(app, /getPublicAccessCopy\(locale\)/);

assert.match(api, /fetchConnectivityProviders/);
assert.match(api, /requestJson<ConnectivityProviderPublicSnapshot>\("\/api\/connectivity\/providers", token\)/);
assert.match(api, /fetchPublicRouteCandidate/);
assert.match(api, /requestJson<PublicRouteCandidateSnapshot>\("\/api\/connectivity\/routes", token\)/);
assert.match(api, /stagePublicRouteCandidate/);
assert.match(api, /"\/api\/connectivity\/routes\/candidate"/);
assert.match(api, /method:\s*"DELETE"/);
assert.match(api, /buildHeaders\(token, \{ mutation: true \}\)/);
assert.doesNotMatch(api, /\/api\/connectivity\/routes\/(verify|cutover)/);
assert.match(types, /interface ConnectivityProviderPublicSnapshot/);
assert.match(types, /interface PublicRouteCandidateSnapshot/);
assert.match(types, /status:\s*"staged-unverified"/);
assert.match(types, /source:\s*"runtime-config"/);
assert.match(types, /managedByChatCockpit:\s*boolean/);
assert.doesNotMatch(types, /machineAdapter/);
assert.match(types, /"adapter-not-implemented"/);

assert.match(view, /status:\s*IntegrationStatusResponse/);
assert.match(view, /status\.localCockpitUrl/);
assert.match(view, /status\.publicCockpitUrl/);
assert.match(view, /status\.localApiBaseUrl/);
assert.match(view, /status\.publicApiBaseUrl/);
assert.match(view, /status\.openapiUrl/);
assert.match(view, /status\.mcp\.endpoint/);
assert.match(view, /status\.mcp\.oauthStatus/);
assert.match(view, /status\.publicApiBaseUrl\?\.startsWith\("https:\/\/"\) === true/);
assert.match(view, /const hasPublicApi = Boolean\(status\.publicApiBaseUrl\)/);
assert.match(view, /!hasPublicApi \? "default" : publicHttpsReady \? "success" : "warning"/);
assert.match(view, /className="summary-entry-link"/);
assert.match(view, /providerStatus:\s*ConnectivityProviderPublicSnapshot \| null/);
assert.match(view, /providerStatusError:\s*string \| null/);
assert.match(view, /providerStatus\.providers\.map/);
assert.match(view, /provider\.displayName/);
assert.match(view, /action\.reason === "adapter-not-implemented"/);
assert.match(view, /provider\.managedByChatCockpit/);
assert.match(view, /provider\.actions[\s\S]*\.filter\(\(action\) => action\.available\)/s);
assert.match(view, /providerUseAppCli/);
assert.match(view, /routeStatus:\s*PublicRouteCandidateSnapshot \| null/);
assert.match(view, /routeStatusError:\s*string \| null/);
assert.match(view, /routeStatus\.canonical\.origin/);
assert.match(view, /routeStatus\.candidate\.origin/);
assert.match(view, /candidateStagedUnverified/);
assert.match(view, /onStageCandidate\(candidateOrigin\.trim\(\), candidateSource\)/);
assert.match(view, /onDiscardCandidate/);
assert.match(view, /ROUTE_CANDIDATE_PROVIDER_SOURCES = new Set<PublicRouteCandidateSource>/);
assert.match(view, /"cloudflare-tunnel"/);
assert.match(view, /"ngrok"/);
assert.match(view, /"frp-client"/);
assert.match(view, /\.filter\(\(provider\) => ROUTE_CANDIDATE_PROVIDER_SOURCES\.has/);
assert.match(view, /routeSourceOptions/);
assert.match(view, /provider\.displayName/);
assert.doesNotMatch(view, /onVerifyCandidate|onCutoverCandidate|verifyCandidate|cutoverCandidate/);
assert.doesNotMatch(view, /Button[^\n]*(Verify|Cutover|切换|验证)/);
assert.match(view, /href="chatcockpit:\/\/settings\/connectivity"/);
assert.doesNotMatch(view, /chatcockpit:\/\/settings\/connectivity\?/);
assert.doesNotMatch(view, /chatcockpit:\/\/settings\/connectivity[\s\S]*(provider|action|planId)=/i);
assert.match(view, /openConnectivityInApp/);
assert.match(view, /connectivityBridgeDescription/);
assert.match(view, /onOpenIntegrations:\s*\(\) => void/);
assert.doesNotMatch(view, /fetch\(|fetchIntegrationStatus|fetchConnectivityProviders|requestJson|setAccessPolicy|machine-token|prepareConnectivityProvider|executeConnectivityProvider/i);
assert.doesNotMatch(view, /planId|stdout|stderr|\/opt\/homebrew|\/usr\/local\/bin|\bbrew\b/i);
assert.doesNotMatch(view, /Button[^\n]*(Install|Upgrade|Uninstall)|Start Tunnel|Cloudflare Login/i);

assert.match(headerI18n, /publicAccess:\s*"公网接入"/);
assert.match(headerI18n, /publicAccess:\s*"Public Access"/);
assert.match(copy, /reachabilityTitle:\s*"可达性概览"/);
assert.match(copy, /publicCockpit:\s*"公网控制台"/);
assert.match(copy, /existingEnvironment:\s*"现有环境"/);
assert.match(copy, /reachabilityTitle:\s*"Reachability overview"/);
assert.match(copy, /publicCockpit:\s*"Public Cockpit"/);
assert.match(copy, /existingEnvironment:\s*"Existing environment"/);
assert.match(copy, /providersTitle:\s*"本机接入组件"/);
assert.match(copy, /providerExternalUnmanaged:\s*"外部环境 · 未接管"/);
assert.match(copy, /providerObserveOnly:\s*"仅观察 · 尚无机器 Adapter"/);
assert.match(copy, /providersTitle:\s*"Machine connectors"/);
assert.match(copy, /providerExternalUnmanaged:\s*"External environment · unmanaged"/);
assert.match(copy, /providerObserveOnly:\s*"Observe only · no machine adapter yet"/);
assert.match(copy, /openConnectivityInApp:\s*"在 ChatCockpit App 中打开"/);
assert.match(copy, /openConnectivityInApp:\s*"Open in ChatCockpit App"/);
assert.match(copy, /不会自动执行安装、升级、卸载或启动 Tunnel/);
assert.match(copy, /never auto-runs install, upgrade, uninstall, or Tunnel startup/);
assert.match(copy, /routeIntentTitle:\s*"候选公网 Route"/);
assert.match(copy, /candidateStagedUnverified:\s*"已暂存 · 未验证"/);
assert.match(copy, /不会执行 DNS\/HTTP\/TLS 验证/);
assert.match(copy, /验证与显式 cutover 将作为后续独立阶段实现/);
assert.match(copy, /routeIntentTitle:\s*"Candidate Public Route"/);
assert.match(copy, /candidateStagedUnverified:\s*"Staged · unverified"/);
assert.match(copy, /performs no DNS\/HTTP\/TLS verification/);
assert.match(copy, /Verification and explicit cutover remain separate later stages/);

assert.doesNotMatch(copy, /cloudflared|ngrok|\bfrpc\b|pinggy|binaryExists|providerInstalled/i);
assert.doesNotMatch(view, /cloudflared|\bfrpc\b|pinggy|binaryExists|providerInstalled/i);
assert.equal((view.match(/"cloudflare-tunnel"/g) ?? []).length, 1);
assert.equal((view.match(/"ngrok"/g) ?? []).length, 1);
assert.equal((view.match(/"frp-client"/g) ?? []).length, 1);
const providerFiction = `${view}\n${copy}`;
assert.doesNotMatch(providerFiction, /provider\s+(is\s+)?installed|provider\s+(is\s+)?ready/i);
assert.match(styles, /\.public-access-provider-status\s*\{/);
assert.match(styles, /\.public-access-provider-primary\s*\{/);
assert.match(styles, /\.public-access-provider-bridge\s*\{/);
assert.match(styles, /\.public-access-route-candidate\s*\{/);
assert.match(styles, /\.public-access-route-form\s*\{/);
assert.match(styles, /\.public-access-route-actions\s*\{/);
assert.match(styles, /\.app-toolbar__group--views\s*\{[\s\S]*overflow-x:\s*auto/s);
assert.match(styles, /\.app-toolbar__group--views \.ant-segmented\s*\{[\s\S]*width:\s*max-content/s);

process.stdout.write("VERIFY_WEB_PUBLIC_ACCESS_OK\n");
