import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");

function read(relativePath: string): string {
  const filePath = path.join(root, relativePath);
  assert.equal(fs.existsSync(filePath), true, `${relativePath} must exist`);
  return fs.readFileSync(filePath, "utf8");
}

const app = read("web/src/App.tsx");
const navigation = read("web/src/navigation.ts");
const sidebar = read("web/src/components/AppSidebar.tsx");
const api = read("web/src/api.ts");
const types = read("web/src/types.ts");
const headerI18n = read("web/src/i18n.ts");
const view = read("web/src/components/PublicAccessView.tsx");
const dashboard = read("web/src/components/DashboardView.tsx");
const copy = read("web/src/i18n/public-access.ts");
const integrationsCopy = read("web/src/i18n/integrations.ts");
const styles = read("web/src/styles.css");

assert.match(app, /type ViewKey = AppViewKey/);
assert.match(navigation, /"publicAccess"/);
assert.match(app, /publicAccess:\s*consolePath\("public-access"\)/);
assert.match(app, /route === "public-access"/);
assert.match(app, /import\("\.\/components\/PublicAccessView"\)/);
assert.match(app, /<AppSidebar/);
assert.match(sidebar, /key:\s*"connectionsPublicAccess"/);
assert.match(app, /<PublicAccessView[\s\S]*status=\{integrationStatus\}/s);
assert.match(app, /exposed=\{health\.exposed\}/);
assert.match(app, /providerStatus=\{connectivityProviderStatus\}/);
assert.match(app, /providerStatusError=\{connectivityProviderStatusError\}/);
assert.match(app, /fetchConnectivityProviders\(token\)/);
assert.match(app, /setConnectivityProviderStatus\(providerResponse\)/);
assert.match(app, /setConnectivityProviderStatusError\(getErrorMessage\(error\)\)/);
assert.match(app, /fetchPublicRouteCandidate\(token\)/);
assert.match(app, /setPublicRouteCandidateStatus\(routeResponse\)/);
assert.match(app, /stagePublicRouteCandidate\(\{ origin, source \}, token\)/);
assert.match(app, /discardPublicRouteCandidate\(token\)/);
assert.match(app, /fetchPublicRouteVerification\(token\)/);
assert.match(app, /verifyPublicRouteCandidate\(candidateId, token\)/);
assert.match(app, /setPublicRouteVerificationStatus\(verificationResponse\)/);
assert.match(app, /routeStatus=\{publicRouteCandidateStatus\}/);
assert.match(app, /routeStatusError=\{publicRouteCandidateError\}/);
assert.match(app, /routeMutating=\{publicRouteCandidateMutating\}/);
assert.match(app, /verificationStatus=\{publicRouteVerificationStatus\}/);
assert.match(app, /verificationStatusError=\{publicRouteVerificationError\}/);
assert.match(app, /routeVerifying=\{publicRouteVerifying\}/);
assert.match(app, /cutoverIntentStatus=\{publicRouteCutoverIntentStatus\}/);
assert.match(app, /cutoverIntentStatusError=\{publicRouteCutoverIntentError\}/);
assert.match(app, /cutoverIntentMutating=\{publicRouteCutoverIntentMutating\}/);
assert.match(app, /onStageCandidate=\{\(origin, source\) => void stageCandidatePublicRoute\(origin, source\)\}/);
assert.match(app, /onDiscardCandidate=\{\(\) => void discardCandidatePublicRoute\(\)\}/);
assert.match(app, /onVerifyCandidate=\{\(candidateId\) => void verifyCandidatePublicRoute\(candidateId\)\}/);
assert.match(app, /fetchPublicRouteCutoverIntent\(token\)/);
assert.match(app, /preparePublicRouteCutoverIntent\(\{ candidateId, verificationId \}, token\)/);
assert.match(app, /cancelPublicRouteCutoverIntent\(token\)/);
assert.match(app, /onPrepareCutoverIntent=\{\(candidateId, verificationId\) => void prepareCandidateCutoverIntent\(candidateId, verificationId\)\}/);
assert.match(app, /onCancelCutoverIntent=\{\(\) => void cancelCandidateCutoverIntent\(\)\}/);
assert.match(app, /fetchPublicRouteBootstrapProof\(token\)/);
assert.match(app, /preparePublicRouteBootstrapProof\(candidateId, token\)/);
assert.match(app, /verifyPublicRouteBootstrapProof\(\{ candidateId, proofId \}, token\)/);
assert.match(app, /cancelPublicRouteBootstrapProof\(token\)/);
assert.match(app, /bootstrapProofStatus=\{publicRouteBootstrapProofStatus\}/);
assert.match(app, /bootstrapProofStatusError=\{publicRouteBootstrapProofError\}/);
assert.match(app, /bootstrapProofMutating=\{publicRouteBootstrapProofMutating\}/);
assert.match(app, /onPrepareBootstrapProof=\{\(candidateId\) => void prepareBootstrapProof\(candidateId\)\}/);
assert.match(app, /onVerifyBootstrapProof=\{\(candidateId, proofId\) => void verifyBootstrapProof\(candidateId, proofId\)\}/);
assert.match(app, /onCancelBootstrapProof=\{\(\) => void cancelBootstrapProof\(\)\}/);
assert.match(app, /onOpenIntegrations=\{\(\) => navigateView\("integrations"\)\}/);
assert.match(app, /getPublicAccessCopy\(locale\)/);

assert.match(api, /fetchConnectivityProviders/);
assert.match(api, /requestJson<ConnectivityProviderPublicSnapshot>\("\/api\/connectivity\/providers", token\)/);
assert.match(api, /fetchPublicRouteCandidate/);
assert.match(api, /requestJson<PublicRouteCandidateSnapshot>\("\/api\/connectivity\/routes", token\)/);
assert.match(api, /stagePublicRouteCandidate/);
assert.match(api, /"\/api\/connectivity\/routes\/candidate"/);
assert.match(api, /method:\s*"DELETE"/);
assert.match(api, /buildHeaders\(token, \{ mutation: true \}\)/);
assert.match(api, /fetchPublicRouteVerification/);
assert.match(api, /"\/api\/connectivity\/routes\/verification"/);
assert.match(api, /verifyPublicRouteCandidate/);
assert.match(api, /"\/api\/connectivity\/routes\/candidate\/verify"/);
assert.match(api, /fetchPublicRouteCutoverIntent/);
assert.match(api, /preparePublicRouteCutoverIntent/);
assert.match(api, /cancelPublicRouteCutoverIntent/);
assert.match(api, /"\/api\/connectivity\/routes\/cutover-intent"/);
assert.match(api, /fetchPublicRouteBootstrapProof/);
assert.match(api, /preparePublicRouteBootstrapProof/);
assert.match(api, /verifyPublicRouteBootstrapProof/);
assert.match(api, /cancelPublicRouteBootstrapProof/);
assert.match(api, /"\/api\/connectivity\/routes\/bootstrap-proof"/);
assert.match(api, /"\/api\/connectivity\/routes\/bootstrap-proof\/verify"/);
assert.doesNotMatch(api, /\/api\/connectivity\/routes\/bootstrap(?:-proof)?\/execute/);
assert.doesNotMatch(api, /\/api\/connectivity\/routes\/cutover(?:\/|"|`)/);
assert.doesNotMatch(api, /\/api\/connectivity\/routes\/cutover-intent\/execute/);
assert.match(types, /interface ConnectivityProviderPublicSnapshot/);
assert.match(types, /interface PublicRouteCandidateSnapshot/);
assert.match(types, /status:\s*"staged-unverified"/);
assert.match(types, /source:\s*"runtime-config"/);
assert.match(types, /interface PublicRouteVerificationSnapshot/);
assert.match(types, /status:\s*"verified" \| "failed"/);
assert.match(types, /"non-public-address"/);
assert.match(types, /"unexpected-oauth-metadata"/);
assert.match(types, /interface PublicRouteCutoverIntent/);
assert.match(types, /status:\s*"pending-machine-execution"/);
assert.match(types, /requiresMachineAuthority:\s*true/);
assert.match(types, /startsStoppedRuntime:\s*false/);
assert.match(types, /startsProviderTunnel:\s*false/);
assert.match(types, /writesProviderSecrets:\s*false/);
assert.match(types, /interface PublicRouteBootstrapProofSnapshot/);
assert.match(types, /status:\s*"prepared" \| "verified"/);
assert.match(types, /"proof-mismatch"/);
assert.doesNotMatch(types, /challenge\s*:/i);
assert.match(types, /managedByChatCockpit:\s*boolean/);
assert.doesNotMatch(types, /machineAdapter/);
assert.match(types, /"adapter-not-implemented"/);
assert.match(types, /lanAccess\?:\s*\{/);
assert.match(types, /"listener-loopback"/);
assert.match(types, /cockpitUrls:\s*string\[\]/);
assert.match(types, /trustedCidrs:\s*string\[\]/);

assert.match(view, /status:\s*IntegrationStatusResponse/);
assert.match(view, /status\.localCockpitUrl/);
assert.match(view, /status\.publicCockpitUrl/);
assert.match(view, /status\.localApiBaseUrl/);
assert.match(view, /status\.publicApiBaseUrl/);
assert.match(view, /status\.openapiUrl/);
assert.match(view, /status\.lanAccess \?\?/);
assert.match(view, /lanAccess\.status/);
assert.match(view, /lanAccess\.cockpitUrls/);
assert.match(view, /lanAccess\.trustedCidrs/);
assert.match(view, /copy\.lanCockpit/);
assert.match(view, /copy\.lanAccessReadyDescription/);
assert.match(view, /copy\.lanAccessLoopbackDescription/);
assert.match(view, /copy\.lanAccessNoTrustedAddressDescription/);
assert.match(view, /status\.mcp\.endpoint/);
assert.match(view, /status\.mcp\.oauthStatus/);
assert.match(view, /status\.publicApiBaseUrl\?\.startsWith\("https:\/\/"\) === true/);
assert.match(view, /const hasPublicApi = Boolean\(status\.publicApiBaseUrl\)/);
assert.match(view, /!hasPublicApi \? "default" : publicHttpsReady \? "success" : "warning"/);
assert.match(view, /className="summary-entry-link"/);
assert.match(view, /providerStatus:\s*ConnectivityProviderPublicSnapshot \| null/);
assert.match(view, /providerStatusError:\s*string \| null/);
assert.match(view, /providerStatus\.providers\.map/);
assert.match(view, /provider\.displayName/);
assert.match(view, /action\.reason === "adapter-not-implemented"/);
assert.match(view, /provider\.managedByChatCockpit/);
assert.match(view, /provider\.actions[\s\S]*\.filter\(\(action\) => action\.available\)/s);
assert.match(view, /providerUseAppCli/);
assert.match(view, /routeStatus:\s*PublicRouteCandidateSnapshot \| null/);
assert.match(view, /routeStatusError:\s*string \| null/);
assert.match(view, /routeStatus\.canonical\.origin/);
assert.match(view, /routeStatus\.candidate\.origin/);
assert.match(view, /candidateStagedUnverified/);
assert.match(view, /verificationStatus:\s*PublicRouteVerificationSnapshot \| null/);
assert.match(view, /routeVerifying:\s*boolean/);
assert.match(view, /onVerifyCandidate:\s*\(candidateId: string\) => void/);
assert.match(view, /cutoverIntentStatus:\s*PublicRouteCutoverIntentSnapshot \| null/);
assert.match(view, /cutoverIntentMutating:\s*boolean/);
assert.match(view, /onPrepareCutoverIntent:\s*\(candidateId: string, verificationId: string\) => void/);
assert.match(view, /onCancelCutoverIntent:\s*\(\) => void/);
assert.match(view, /bootstrapProofStatus:\s*PublicRouteBootstrapProofSnapshot \| null/);
assert.match(view, /onPrepareBootstrapProof:\s*\(candidateId: string\) => void/);
assert.match(view, /onVerifyBootstrapProof:\s*\(candidateId: string, proofId: string\) => void/);
assert.match(view, /onCancelBootstrapProof:\s*\(\) => void/);
assert.match(view, /const bootstrapMode = routeStatus\?\.canonical\.configured === false/);
assert.match(view, /rawBootstrapProof\.candidateId === routeStatus\?\.candidate\?\.id/);
assert.match(view, /rawBootstrapProof\.candidateOrigin === routeStatus\?\.candidate\?\.origin/);
assert.match(view, /onPrepareBootstrapProof\(routeStatus\.candidate!\.id\)/);
assert.match(view, /onVerifyBootstrapProof\(routeStatus\.candidate!\.id, bootstrapProof\.id\)/);
assert.match(view, /onCancelBootstrapProof/);
assert.match(view, /const currentVerification = verificationStatus\?\.verification \?\? null/);
assert.match(view, /currentVerification\?\.candidateId === routeStatus\?\.candidate\?\.id/);
assert.match(view, /verification\.checks\.dns/);
assert.match(view, /verification\.checks\.tls/);
assert.match(view, /verification\.checks\.reachability/);
assert.match(view, /verification\.checks\.identity/);
assert.match(view, /verification\.checks\.oauth/);
assert.match(view, /onStageCandidate\(candidateOrigin\.trim\(\), candidateSource\)/);
assert.match(view, /onDiscardCandidate/);
assert.match(view, /onVerifyCandidate\(routeStatus\.candidate!\.id\)/);
assert.match(view, /ROUTE_CANDIDATE_PROVIDER_SOURCES = new Set<PublicRouteCandidateSource>/);
assert.match(view, /"cloudflare-tunnel"/);
assert.match(view, /"ngrok"/);
assert.match(view, /"frp-client"/);
assert.match(view, /\.filter\(\(provider\) => ROUTE_CANDIDATE_PROVIDER_SOURCES\.has/);
assert.match(view, /routeSourceOptions/);
assert.match(view, /provider\.displayName/);
assert.match(view, /verifyCandidateRoute/);
assert.match(view, /rawCutoverIntent\.candidateId === routeStatus\?\.candidate\?\.id/);
assert.match(view, /rawCutoverIntent\.verificationId === verification\?\.id/);
assert.match(view, /copy\.prepareCutoverIntent/);
assert.match(view, /copy\.cancelCutoverIntent/);
assert.match(view, /onPrepareCutoverIntent\(routeStatus\.candidate!\.id, verification\.id\)/);
assert.doesNotMatch(view, /onCutoverCandidate|executeCutover|cutoverCandidate|executeBootstrap/);
assert.doesNotMatch(view, /server\.env|launchctl|\.restart\(|LifecycleAction|runtimeRestart/i);
assert.doesNotMatch(view, /challenge\s*[:=]/i);
assert.match(view, /href="chatcockpit:\/\/settings\/connectivity"/);
assert.doesNotMatch(view, /chatcockpit:\/\/settings\/connectivity\?/);
assert.doesNotMatch(view, /chatcockpit:\/\/settings\/connectivity[\s\S]*(provider|action|planId)=/i);
assert.match(view, /openConnectivityInApp/);
assert.match(view, /connectivityBridgeDescription/);
assert.match(view, /onOpenIntegrations:\s*\(\) => void/);
assert.doesNotMatch(view, /fetch\(|fetchIntegrationStatus|fetchConnectivityProviders|requestJson|setAccessPolicy|machine-token|prepareConnectivityProvider|executeConnectivityProvider/i);
assert.doesNotMatch(view, /planId|stdout|stderr|resolvedAddress|ipAddress|\/opt\/homebrew|\/usr\/local\/bin|\bbrew\b/i);
assert.doesNotMatch(view, /Button[^\n]*(Install|Upgrade|Uninstall)|Start Tunnel|Cloudflare Login/i);

assert.match(headerI18n, /publicAccess:\s*"公网接入"/);
assert.match(headerI18n, /integrations:\s*"集成与授权"/);
assert.match(headerI18n, /publicAccess:\s*"Public Access"/);
assert.match(headerI18n, /integrations:\s*"Integrations & Access"/);
assert.match(copy, /statusOverviewTitle:\s*"当前公网状态"/);
assert.match(copy, /addressesTitle:\s*"访问地址"/);
assert.match(copy, /protocolHealthTitle:\s*"协议健康"/);
assert.match(copy, /publicCockpit:\s*"公网控制台"/);
assert.match(copy, /lanCockpit:\s*"局域网控制台"/);
assert.match(copy, /lanAccessReady:\s*"可访问"/);
assert.match(copy, /lanAccessLoopbackOnly:\s*"仅监听本机"/);
assert.match(copy, /trustedLanCidrs:\s*"可信局域网"/);
assert.match(copy, /进入控制台后仍然需要 Owner 身份认证/);
assert.match(copy, /existingEnvironment:\s*"现有环境"/);
assert.match(copy, /statusOverviewTitle:\s*"Current public status"/);
assert.match(copy, /addressesTitle:\s*"Addresses"/);
assert.match(copy, /protocolHealthTitle:\s*"Protocol health"/);
assert.match(copy, /publicCockpit:\s*"Public Cockpit"/);
assert.match(copy, /lanCockpit:\s*"LAN Cockpit"/);
assert.match(copy, /lanAccessReady:\s*"Reachable"/);
assert.match(copy, /lanAccessLoopbackOnly:\s*"Loopback only"/);
assert.match(copy, /trustedLanCidrs:\s*"Trusted LAN"/);
assert.match(copy, /Owner authentication is still required/);
assert.match(copy, /existingEnvironment:\s*"Existing environment"/);
assert.match(copy, /providersTitle:\s*"本机接入组件"/);
assert.match(copy, /providerDetailsTitle:\s*"查看组件状态"/);
assert.match(copy, /接入组件属于机器侧辅助设置/);
assert.match(copy, /providerExternalUnmanaged:\s*"外部环境 · 未接管"/);
assert.match(copy, /providerObserveOnly:\s*"仅观察 · 尚无机器 Adapter"/);
assert.match(copy, /providersTitle:\s*"Machine connectors"/);
assert.match(copy, /providerDetailsTitle:\s*"View connector status"/);
assert.match(copy, /Connectors are auxiliary machine-side settings/);
assert.match(copy, /providerExternalUnmanaged:\s*"External environment · unmanaged"/);
assert.match(copy, /providerObserveOnly:\s*"Observe only · no machine adapter yet"/);
assert.match(copy, /openConnectivityInApp:\s*"在 ChatCockpit App 中打开"/);
assert.match(copy, /openConnectivityInApp:\s*"Open in ChatCockpit App"/);
assert.match(copy, /不会自动执行安装、升级、卸载或启动 Tunnel/);
assert.match(copy, /never auto-runs install, upgrade, uninstall, or Tunnel startup/);
assert.match(copy, /workflowTitle:\s*"公网接入流程"/);
assert.match(copy, /workflowSetup:\s*"准备"/);
assert.match(copy, /workflowVerify:\s*"验证"/);
assert.match(copy, /workflowCutover:\s*"切换"/);
assert.match(copy, /workflowLive:\s*"在线"/);
assert.match(copy, /changePublicAccess:\s*"更换公网接入"/);
assert.match(copy, /closePublicAccessMaintenance:\s*"收起维护流程"/);
assert.match(copy, /routeIntentTitle:\s*"候选公网 Route"/);
assert.match(copy, /candidateStagedUnverified:\s*"已暂存 · 未验证"/);
assert.match(copy, /candidateVerified:\s*"已验证"/);
assert.match(copy, /verifyCandidateRoute:\s*"验证候选"/);
assert.match(copy, /public-unicast DNS 与固定 IP HTTPS 探针/);
assert.match(copy, /prepareCutoverIntent:\s*"准备 Cutover Intent"/);
assert.match(copy, /cutoverIntentPending:\s*"待机器执行"/);
assert.match(copy, /replacement cutover 与首次公网 Bootstrap 都只能在 App \/ CLI Machine Authority 中执行/);
assert.match(copy, /bootstrapProofTitle:\s*"首次公网身份验证"/);
assert.match(copy, /bootstrapPrepared:\s*"Challenge 已准备"/);
assert.match(copy, /bootstrapVerified:\s*"身份已验证"/);
assert.match(copy, /verifyBootstrapProof:\s*"验证公网身份"/);
assert.match(copy, /Web 不提供机器执行/);
assert.match(copy, /失败时回滚为 local-only/);
assert.match(copy, /已停止的 Runtime 不会被自动启动/);
assert.match(integrationsCopy, /lanCockpit:\s*"局域网控制台"/);
assert.match(integrationsCopy, /lanCockpit:\s*"LAN Cockpit"/);
assert.match(dashboard, /integrationStatus\?\.lanAccess\?\.cockpitUrls\[0\]/);
assert.match(dashboard, /integrationsCopy\.lanCockpit/);
assert.match(styles, /\.public-access-status-tags/);
assert.match(styles, /\.public-access-endpoint-list/);

assert.match(copy, /workflowTitle:\s*"Public Access workflow"/);
assert.match(copy, /workflowSetup:\s*"Setup"/);
assert.match(copy, /workflowVerify:\s*"Verify"/);
assert.match(copy, /workflowCutover:\s*"Cutover"/);
assert.match(copy, /workflowLive:\s*"Live"/);
assert.match(copy, /changePublicAccess:\s*"Change Public Access"/);
assert.match(copy, /closePublicAccessMaintenance:\s*"Collapse maintenance workflow"/);
assert.match(copy, /routeIntentTitle:\s*"Candidate Public Route"/);
assert.match(copy, /candidateStagedUnverified:\s*"Staged · unverified"/);
assert.match(copy, /candidateVerified:\s*"Verified"/);
assert.match(copy, /verifyCandidateRoute:\s*"Verify candidate"/);
assert.match(copy, /public-unicast DNS and pinned-address HTTPS probes/);
assert.match(copy, /prepareCutoverIntent:\s*"Prepare Cutover Intent"/);
assert.match(copy, /cutoverIntentPending:\s*"Pending machine execution"/);
assert.match(copy, /Replacement cutover for an existing canonical and first-public Bootstrap both execute only under App \/ CLI Machine Authority/);
assert.match(copy, /bootstrapProofTitle:\s*"Initial public identity proof"/);
assert.match(copy, /bootstrapPrepared:\s*"Challenge prepared"/);
assert.match(copy, /bootstrapVerified:\s*"Identity verified"/);
assert.match(copy, /verifyBootstrapProof:\s*"Verify public identity"/);
assert.match(copy, /Web provides no machine execution control/);
assert.match(copy, /failure rollback to local-only/);
assert.match(copy, /a stopped Runtime is never started automatically/);

assert.match(view, /<Steps/);
assert.match(view, /copy\.statusOverviewTitle/);
assert.match(view, /public-access-status-grid/);
assert.doesNotMatch(view, /copy\.reachabilityTitle|copy\.protocolsTitle|copy\.diagnosticsTitle/);
assert.match(view, /const workflowStage =/);
assert.match(view, /const \[onlineMaintenanceExpanded, setOnlineMaintenanceExpanded\] = useState\(false\)/);
assert.match(view, /const workflowStatusError = Boolean/);
assert.match(view, /const isOnlineSteadyState = workflowStage === 3/);
assert.match(view, /const displayWorkflowStage = isOnlineSteadyState && onlineMaintenanceExpanded \? 0 : workflowStage/);
assert.match(view, /const showWorkflowCard = !isOnlineSteadyState \|\| onlineMaintenanceExpanded/);
assert.match(view, /const showVerificationDetails = displayWorkflowStage === 1 \|\| workflowVerificationFailed/);
assert.match(view, /const showCandidateEditor = displayWorkflowStage === 0/);
assert.match(view, /const showCutoverDetails = displayWorkflowStage === 2/);
assert.match(view, /const showRouteWorkspace = displayWorkflowStage !== 3/);
assert.match(view, /\{showWorkflowCard \? \(/);
assert.match(view, /current=\{displayWorkflowStage\}/);
assert.match(view, /copy\.changePublicAccess/);
assert.match(view, /copy\.closePublicAccessMaintenance/);
assert.match(view, /setOnlineMaintenanceExpanded\(\(expanded\) => !expanded\)/);
assert.match(view, /\{showRouteWorkspace \? \(/);
assert.match(view, /verification && showVerificationDetails/);
assert.match(view, /bootstrapVerification && showVerificationDetails/);
assert.match(view, /showCutoverDetails && cutoverIntent/);
assert.match(view, /\{showCandidateEditor \? \(/);
assert.doesNotMatch(view, /copy\.connectionPathTitle|copy\.connectionPathDescription/);
assert.match(styles, /\.public-access-workflow-steps\s*\{/);
assert.match(styles, /\.public-access-status-actions\s*\{/);
assert.match(styles, /\.public-access-status-grid\s*\{/);
assert.match(styles, /\.public-access-status-block\s*\{/);
assert.doesNotMatch(copy, /cloudflared|ngrok|\bfrpc\b|pinggy|binaryExists|providerInstalled/i);
assert.doesNotMatch(view, /cloudflared|\bfrpc\b|pinggy|binaryExists|providerInstalled/i);
assert.equal((view.match(/"cloudflare-tunnel"/g) ?? []).length, 1);
assert.equal((view.match(/"ngrok"/g) ?? []).length, 1);
assert.equal((view.match(/"frp-client"/g) ?? []).length, 1);
const providerFiction = `${view}\n${copy}`;
assert.doesNotMatch(providerFiction, /provider\s+(is\s+)?installed|provider\s+(is\s+)?ready/i);
assert.match(view, /<Collapse/);
assert.match(view, /className="public-access-provider-details"/);
assert.match(view, /copy\.providerDetailsTitle/);
assert.match(styles, /\.public-access-provider-details \.ant-collapse-header\s*\{/);
assert.match(styles, /\.public-access-provider-details__label\s*\{/);
assert.match(styles, /\.public-access-provider-status\s*\{/);
assert.match(styles, /\.public-access-provider-primary\s*\{/);
assert.match(styles, /\.public-access-provider-bridge\s*\{/);
assert.match(styles, /\.public-access-route-candidate\s*\{/);
assert.match(styles, /\.public-access-verification-grid\s*\{/);
assert.match(styles, /\.public-access-verification-check\s*\{/);
assert.match(styles, /\.public-access-route-form\s*\{/);
assert.match(styles, /\.public-access-route-actions\s*\{/);
assert.match(styles, /\.app-sidebar\s*\{[\s\S]*flex:\s*0 0 232px/s);
assert.match(styles, /\.app-sidebar--collapsed\s*\{[\s\S]*width:\s*72px/s);
assert.match(styles, /@media \(max-width: 820px\)[\s\S]*\.app-sidebar:not\(\.app-sidebar--mobile\)[\s\S]*display:\s*none/s);
assert.match(sidebar, /<Drawer/);

process.stdout.write("VERIFY_WEB_PUBLIC_ACCESS_OK\n");
